android {
    namespace = "me.aap.fermatamodfs.auto.dear.google.why.bingo2.fs.addon.radio"
    defaultConfig {
        versionCode 1
        versionName "1.0"
    }
}

ext {
    addons = [
            [
                    name       : 'radio',
                    icon       : 'radio',
                    class      : 'me.aap.fermatamodfs.auto.dear.google.why.bingo2.fs.addon.radio.RadioAddon',
                    order      : 2,
                    hasSettings: true
            ]
    ]
}

dependencies {
    implementation project(':utils')
    implementation project(':fermata')
    implementation "androidx.media:media:${ANDROIDX_MEDIA_VERSION}"
    implementation "androidx.appcompat:appcompat:${ANDROIDX_APPCOMPAT_VERSION}"
    implementation "androidx.constraintlayout:constraintlayout:${ANDROIDX_CONSTRAINTLAYOUT_VERSION}"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:${ANDROIDX_SWIPEREFRESHLAYOUT_VERSION}"
    implementation "com.google.android.material:material:${ANDROID_MATERIAL_VERSION}"
}
